-- Align catalog schema with the current JPA entity model

ALTER TABLE IF EXISTS catalog.category
  ADD COLUMN IF NOT EXISTS image_url VARCHAR(512),
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS catalog.product
  ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS catalog.product_variant
  ADD COLUMN IF NOT EXISTS variant_attributes JSONB,
  ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS weight NUMERIC(8, 3),
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS catalog.inventory
  ADD COLUMN IF NOT EXISTS warehouse_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS catalog.product_attribute
  ADD COLUMN IF NOT EXISTS type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
  ADD COLUMN IF NOT EXISTS display_order INTEGER NOT NULL DEFAULT 0;
